---
title: "amer.comm.survey"
author: "Anita Owens"
date: "April 12, 2016"
output: html_document
---
load it in
load("<FileName>.RDA")
```{r}
# Load in your data--my way
acs_url <- "http://s3.amazonaws.com/assets.datacamp.com/production/course_810/AC_Survey_Subset.RData"

load(url("http://s3.amazonaws.com/assets.datacamp.com/production/course_810/AC_Survey_Subset.RData"))

#load data--datacamp way
acs_url <- "http://s3.amazonaws.com/assets.datacamp.com/production/course_810/AC_Survey_Subset.RData"
load(url(acs_url))

# Investigate first 20 observations
head(AC_Survey_Subset, 20)
```
preparing data for further analysis
```{r}
# Load in the dplyr package and convert AC_Survey_Subset to tbl_df

library(dplyr)

#convert to a table
AC_Survey_Subset <- tbl_df(AC_Survey_Subset) 

#remove na values--this is one way to do it but don't run code
AC_Survey_Subset<-na.omit(AC_Survey_Subset)

# Use the pipe operator and chaining 
AC_Survey_Subset_Cleaned <- AC_Survey_Subset %>%                 na.omit(AC_Survey_Subset) %>%                                filter(AC_Survey_Subset, SCHL == c(21, 22, 24)) %>%
        group_by(SCHL)

#2nd attempt
#step1--works
AC_Survey_Subset_Cleaned <- na.omit(AC_Survey_Subset) 

#step2-
AC_Survey_Subset_Cleaned <- AC_Survey_Subset %>%
na.omit(AC_Survey_Subset)%>%
filter(AC_Survey_Subset, SCHL==21 | SCHL==22 | SCHL==24)

```
mtcars testing filter
```{r}
mpg22<-filter(mtcars, mpg>22)
dim(mpg22)
#9 11

#conditional statement
mpgtest<-filter(mtcars, mpg== 21 & mpg==32)
dim(mpgtest)
#0 11

#subsets only the variables that meet both conditions
mpgtest2<-filter(mtcars, mpg== 22.8 | mpg==30.4)
dim(mpgtest2)
#4 11

#equivalent to and
cyl<-filter(mtcars, cyl>= 8 | cyl<=4 )
dim(cyl)
#25 11

#the & is a conditional statement
cyl2<-filter(mtcars, cyl>= 8 & mpg<=4 )
dim(cyl2)
#0 11
```

