---
title: "Course Project 1"
author: "Anita Owens"
date: "January 9, 2016"
output: html_document
---

http://www.r-bloggers.com/using-r-common-errors-in-table-import/

#handling date times in R
http://biostat.mc.vanderbilt.edu/wiki/pub/Main/ColeBeck/datestimes.pdf

```{r}
getwd()
setwd("/Users/anitaowens/Documents/ExData_Plotting1")
setwd("/Users/anitaowens/Documents/datasciencecoursera")
setwd("/Users/anitaowens/Documents/datasciencecoursera/data")
setwd("/Users/anitaowens/Documents/datasciencecoursera/EDA_Course_Materials")
```

loading data
```{r}
library(zoo)
library(xts)

#test set
abc <- read.table("test.txt", sep=";", na.strings="?", header=T, stringsAsFactors=FALSE)
abc$Date<-as.Date(abc$Date, format="%d/%m/%Y")
#abc$Time<-sub(".* ", "", abc$Time)
#abc$Time<-strptime(abc$Time, format="%H:%M:%S")
#abc$Time<-as.POSIXlt(abc$Time)
str(abc)
plot(abc$Date, abc$Global_active_power, type = "l", ylab = "Global Active Power (kilowatts)", xlab = " ")

#don't run code
def<-abc[ which(abc$Date>="2007-02-01" & abc$Date<="2007-02-02"),]
plot(def$Date, def$Global_active_power, type = "l", ylab = "Global Active Power (kilowatts)", xlab = " ")
axis.POSIXct(side=1, at=cut(def$Date, "days"), format="%d")


#download and unzip from website
setwd("/Users/anitaowens/Documents/datasciencecoursera")
if(!file.exists("./data")){dir.create("./data")}
file.url<-'https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip'
download.file(file.url,destfile='./data/power_consumption.zip')
unzip('./data/power_consumption.zip',exdir='./data',overwrite=TRUE)
setwd("/Users/anitaowens/Documents/datasciencecoursera/data")

#actual data
library(data.table)
hpc <- read.table("household_power_consumption.txt", sep=";",na.strings="?", header=T,  stringsAsFactors=FALSE)
hpc$Date<-as.Date(hpc$Date, format="%d/%m/%Y")
hpc$Time<--sub(".* ", "", hpc$Time)
str(hpc)
#subsetting dates needed
epc_data<-hpc[ which(hpc$Date>="2007-02-01" & hpc$Date<="2007-02-02"),]
epc_data$Time<-strptime(epc_data$Time, format="%H:%M:%S")
str(epc_data)
```
Plot #1

```{r}
hist(epc_data$Global_active_power,breaks=11, main="Global Active Power", col="red",  xlab="Global Active Power (kilowatts)")

dev.copy(png, file="plot1.png",width=480,height=480)
dev.off()

```
Plot #2
 

combining date and time
```{r}
library(lubridate)
hpc_data <- read.table("household_power_consumption.txt", sep=";",na.strings="?", header=T,  stringsAsFactors=FALSE)

hpc_data$date_time=dmy_hms(paste(hpc_data$Date, hpc_data$Time))

hpc_data$Date<-as.Date(hpc_data$Date, format="%d/%m/%Y")
str(hpc_data)
#subsetting
hpc<-hpc_data[ which(hpc_data$Date>="2007-02-01" & hpc_data$Date<="2007-02-02"),]
str(hpc)

#plot
plot(hpc$date_time, hpc$Global_active_power, type = "l", ylab = "Global Active Power (kilowatts)", xlab = " ")

dev.copy(png, file="plot2.png",width=480,height=480)
dev.off()
```
Plot 3
```{r}
#first line
plot(hpc$date_time, hpc$Sub_metering_1, type = "l", ylim=c(0.0,38), ylab = "Energy Submetering", xlab = " ")

#2nd line
par(new = T)
plot(hpc$date_time, hpc$Sub_metering_2, type = "l", ylim=c(0.0,38), col="red", axes = T, xlab=" ", ylab = "")

#3rd line
par(new = T)
plot(hpc$date_time, hpc$Sub_metering_3, type = "l", ylim=c(0.0,38), col="blue", axes = T, xlab=" ", ylab = " ")

#legend-run in R not IDE
legend(x="topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = c(1,1,1), lwd = c(1.5,1.5,1.5), col = c("black", "red", "blue"))

```

4th plot
```{r}
#Dear fellow classmate:  I know that the 3rd graph is wrong.  I couldn't get it to work and I ran out of time so I understand that I will lose points for plot 4.
#plot1-upper left
#reading data into table
hpc_data <- read.table("household_power_consumption.txt", sep=";",na.strings="?", header=T,  stringsAsFactors=FALSE)

#loading library
library(lubridate)

#pasting date/times
hpc_data$date_time=dmy_hms(paste(hpc_data$Date, hpc_data$Time))

#formatting date variable
hpc_data$Date<-as.Date(hpc_data$Date, format="%d/%m/%Y")

#subsetting
hpc<-hpc_data[ which(hpc_data$Date>="2007-02-01" & hpc_data$Date<="2007-02-02"),]

#4 graphs arranged in 2 rows and 2 columns
par(mfrow=c(2,2))

#plot 1
plot(hpc$date_time, hpc$Global_active_power, type = "l", ylab = "Global Active Power", xlab = " ")

#plot2--across
plot(hpc$date_time, hpc$Voltage, type = "l", ylab = "Voltage", xlab = "datetime")

#plot 3--bottom
plot(hpc$date_time, hpc$Sub_metering_1, type = "l", ylim=c(0.0,38), ylab = "Energy Sub metering", xlab = " ")
par(new = T)
plot(hpc$date_time, hpc$Sub_metering_2, type = "l", ylim=c(0.0,38), col="red", axes = T, xlab=" ", ylab = "")
par(new = T)
plot(hpc$date_time, hpc$Sub_metering_3, type = "l", ylim=c(0.0,38), col="blue", axes = T, xlab=" ", ylab = " ")
legend(x="topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = c(1,1,1), lwd = c(1.5,1.5,1.5), col = c("black", "red", "blue"))

#plot4--lower bottom right
plot(hpc$date_time, hpc$Global_reactive_power, type = "l", ylab = "Global_reactive_power", xlab = "datetime")

dev.copy(png, file="plot4.png",width=480,height=480)
dev.off()
```
inizio data

http://www.sthda.com/english/wiki/r-xlsx-package-a-quick-start-guide-to-manipulate-excel-files-in-r#read-an-excel-file
```{r}
library(xlsx)
library(ggplot2)
sd<-read.xlsx("sd.xlsx", 1, header=TRUE, colClasses=NA)
head(sd[, 1:3])
sd$date<-as.Date(sd$date, format="%d/%m/%Y")
str(sd$date)

qplot(facebook.shares, date, data=sd)

qplot(data=sd, x=date, binwidth=.50, color = I('#66CC99'), fill = I('#F79420'))

```

import csv
http://www.cookbook-r.com/Data_input_and_output/Loading_data_from_a_file/
```{r}
mod <- read.csv("~/Documents/datasciencecoursera/mod.csv", sep=";", header=TRUE)
head(mod)
View(mod)

#write csv file into a spreadsheet
library(xlsx)
write.xlsx(x, file, sheetName="Sheet1", 
  col.names=TRUE, row.names=TRUE, append=FALSE)

#use for very large data frames
write.xlsx2(x, file, sheetName="Sheet1",
  col.names=TRUE, row.names=TRUE, append=FALSE)

write.xlsx(mod1, file="jan.mar.xlsx", sheetName = "Sheet1", col.names=TRUE, row.names=TRUE, append=FALSE)
```

